Class {
	#name : #BrGtDarkThemeHighContrast,
	#superclass : #BrGtAbstractTheme,
	#category : #'BVC-Theme-DarkHighContrast'
}

{ #category : #'class defaults' }
BrGtDarkThemeHighContrast class >> buttonThemeClass [
	^ BrGtButtonDarkTheme
]

{ #category : #'class defaults' }
BrGtDarkThemeHighContrast class >> colorsClass [
	^ BrGtDarkThemeColorsHighContrast
]

{ #category : #'class defaults' }
BrGtDarkThemeHighContrast class >> defaultThemeClass [
	^ BrGtDefaultDarkTheme
]

{ #category : #'class defaults' }
BrGtDarkThemeHighContrast class >> headerThemeClass [
	^ BrGtHeaderDarkTheme
]
