Class {
	#name : #CgtGlamorousTypographySubTheme,
	#superclass : #BlSubTheme,
	#category : #'BVC-Theme-GT'
}

{ #category : #accessing }
CgtGlamorousTypographySubTheme >> bodyFontSize [ ^ 13 ]
{ #category : #accessing }
CgtGlamorousTypographySubTheme >> groupHeadingFontSize [ ^ 14 ]
{ #category : #accessing }
CgtGlamorousTypographySubTheme >> supportingFontSize [ ^ 11 ]
{ #category : #accessing }
CgtGlamorousTypographySubTheme >> titleFontSize [ ^ 16 ]
{ #category : #accessing }
CgtGlamorousTypographySubTheme >> metadataFontSize [ ^ 11 ]
